
package com.thomsonlearning.ws._80.ssows;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.tl.ssows.ws.AddGroupParameters;
import com.tl.ssows.ws.AddResourceItemParameters;
import com.tl.ssows.ws.AddUniqueMemberParameters;
import com.tl.ssows.ws.AddUserParameters;
import com.tl.ssows.ws.CrmsParameters;
import com.tl.ssows.ws.DeleteGroupParameters;
import com.tl.ssows.ws.DeleteUserParameters;
import com.tl.ssows.ws.DoesUserExistParameters;
import com.tl.ssows.ws.GetDirectGroupMembershipParameters;
import com.tl.ssows.ws.GetDirectGroupMembershipResult;
import com.tl.ssows.ws.GetGroupParameters;
import com.tl.ssows.ws.GetGroupsProtectingHostURLParameters;
import com.tl.ssows.ws.GetTokenFromGuidParameters;
import com.tl.ssows.ws.GetTokenParameters;
import com.tl.ssows.ws.GetUserParameters;
import com.tl.ssows.ws.GetUsersParameters;
import com.tl.ssows.ws.HasAccessToParameters;
import com.tl.ssows.ws.IsInstructorParameters;
import com.tl.ssows.ws.IsMemberOfParameters;
import com.tl.ssows.ws.IsUrlProtectedParameters;
import com.tl.ssows.ws.ModifyGroupParameters;
import com.tl.ssows.ws.ModifyUserParameters;
import com.tl.ssows.ws.PasswordResetKeyParameters;
import com.tl.ssows.ws.RefreshTokenParameters;
import com.tl.ssows.ws.RemoveResourceItemParameters;
import com.tl.ssows.ws.RemoveUniqueMemberParameters;
import com.tl.ssows.ws.RenameParameters;
import com.tl.ssows.ws.RestrictionParameters;
import com.tl.ssows.ws.SSOwsResult;
import com.tl.ssows.ws.ValidatedInstructorParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SSOwsPort", targetNamespace = "http://ws.thomsonlearning.com:80/ssows")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.tl.ssows.ObjectFactory.class,
    com.tl.ssows.parameters.ObjectFactory.class,
    com.tl.ssows.ws.ObjectFactory.class,
    language_builtins.lang.ObjectFactory.class
})
public interface SSOwsPort {


    /**
     * 
     * @param renameParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "renameResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "renameResponse")
    public SSOwsResult rename(
        @WebParam(name = "rename", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "renameParameters")
        RenameParameters renameParameters);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getVersionResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getVersionResponse")
    public String getVersion();

    /**
     * 
     * @param getUserParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "getUserResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getUserResponse")
    public SSOwsResult getUser(
        @WebParam(name = "getUser", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getUserParameters")
        GetUserParameters getUserParameters);

    /**
     * 
     * @param getGroupParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "getGroupResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getGroupResponse")
    public SSOwsResult getGroup(
        @WebParam(name = "getGroup", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getGroupParameters")
        GetGroupParameters getGroupParameters);

    /**
     * 
     * @param addGroupParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "addGroupResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "addGroupResponse")
    public SSOwsResult addGroup(
        @WebParam(name = "addGroup", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "addGroupParameters")
        AddGroupParameters addGroupParameters);

    /**
     * 
     * @param getTokenParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "getTokenResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getTokenResponse")
    public SSOwsResult getToken(
        @WebParam(name = "getToken", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getTokenParameters")
        GetTokenParameters getTokenParameters);

    /**
     * 
     * @param addUserParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "addUserResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "addUserResponse")
    public SSOwsResult addUser(
        @WebParam(name = "addUser", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "addUserParameters")
        AddUserParameters addUserParameters);

    /**
     * 
     * @param deleteUserParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "deleteUserResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "deleteUserResponse")
    public SSOwsResult deleteUser(
        @WebParam(name = "deleteUser", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "deleteUserParameters")
        DeleteUserParameters deleteUserParameters);

    /**
     * 
     * @param deleteGroupParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "deleteGroupResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "deleteGroupResponse")
    public SSOwsResult deleteGroup(
        @WebParam(name = "deleteGroup", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "deleteGroupParameters")
        DeleteGroupParameters deleteGroupParameters);

    /**
     * 
     * @param getUsersParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "getUsersResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getUsersResponse")
    public SSOwsResult getUsers(
        @WebParam(name = "getUsers", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getUsersParameters")
        GetUsersParameters getUsersParameters);

    /**
     * 
     * @param isMemberOfParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "isMemberOfResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "isMemberOfResponse")
    public SSOwsResult isMemberOf(
        @WebParam(name = "isMemberOf", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "isMemberOfParameters")
        IsMemberOfParameters isMemberOfParameters);

    /**
     * 
     * @param modifyUserParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "modifyUserResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "modifyUserResponse")
    public SSOwsResult modifyUser(
        @WebParam(name = "modifyUser", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "modifyUserParameters")
        ModifyUserParameters modifyUserParameters);

    /**
     * 
     * @param restrictionParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "restrictionRemoveFromUserResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "restrictionRemoveFromUserResponse")
    public SSOwsResult restrictionRemoveFromUser(
        @WebParam(name = "restrictionRemoveFromUser", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "restrictionParameters")
        RestrictionParameters restrictionParameters);

    /**
     * 
     * @param restrictionParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "restrictionAddToUserResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "restrictionAddToUserResponse")
    public SSOwsResult restrictionAddToUser(
        @WebParam(name = "restrictionAddToUser", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "restrictionParameters")
        RestrictionParameters restrictionParameters);

    /**
     * 
     * @param hasAccessToParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "hasAccessToResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "hasAccessToResponse")
    public SSOwsResult hasAccessTo(
        @WebParam(name = "hasAccessTo", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "hasAccessToParameters")
        HasAccessToParameters hasAccessToParameters);

    /**
     * 
     * @param doesUserExistParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "doesUserExistResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "doesUserExistResponse")
    public SSOwsResult doesUserExist(
        @WebParam(name = "doesUserExist", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "doesUserExistParameters")
        DoesUserExistParameters doesUserExistParameters);

    /**
     * 
     * @param modifyGroupParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "modifyGroupResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "modifyGroupResponse")
    public SSOwsResult modifyGroup(
        @WebParam(name = "modifyGroup", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "modifyGroupParameters")
        ModifyGroupParameters modifyGroupParameters);

    /**
     * 
     * @param isUrlProtectedParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "isUrlProtectedResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "isUrlProtectedResponse")
    public SSOwsResult isUrlProtected(
        @WebParam(name = "isUrlProtected", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "isUrlProtectedParameters")
        IsUrlProtectedParameters isUrlProtectedParameters);

    /**
     * 
     * @param string
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "validateTokenResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "validateTokenResponse")
    public SSOwsResult validateToken(
        @WebParam(name = "validateToken", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "string")
        String string);

    /**
     * 
     * @param addUniqueMemberParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "addUniqueMemberResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "addUniqueMemberResponse")
    public SSOwsResult addUniqueMember(
        @WebParam(name = "addUniqueMember", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "addUniqueMemberParameters")
        AddUniqueMemberParameters addUniqueMemberParameters);

    /**
     * 
     * @param addResourceItemParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "addResourceItemResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "addResourceItemResponse")
    public SSOwsResult addResourceItem(
        @WebParam(name = "addResourceItem", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "addResourceItemParameters")
        AddResourceItemParameters addResourceItemParameters);

    /**
     * 
     * @param removeUniqueMemberParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "removeUniqueMemberResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "removeUniqueMemberResponse")
    public SSOwsResult removeUniqueMember(
        @WebParam(name = "removeUniqueMember", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "removeUniqueMemberParameters")
        RemoveUniqueMemberParameters removeUniqueMemberParameters);

    /**
     * 
     * @param removeResourceItemParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "removeResourceItemResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "removeResourceItemResponse")
    public SSOwsResult removeResourceItem(
        @WebParam(name = "removeResourceItem", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "removeResourceItemParameters")
        RemoveResourceItemParameters removeResourceItemParameters);

    /**
     * 
     * @param isInstructorParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "isInstructorResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "isInstructorResponse")
    public SSOwsResult isInstructor(
        @WebParam(name = "isInstructor", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "isInstructorParameters")
        IsInstructorParameters isInstructorParameters);

    /**
     * 
     * @param getTokenFromGuidParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "getTokenFromGuidResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getTokenFromGuidResponse")
    public SSOwsResult getTokenFromGuid(
        @WebParam(name = "getTokenFromGuid", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getTokenFromGuidParameters")
        GetTokenFromGuidParameters getTokenFromGuidParameters);

    /**
     * 
     * @param refreshTokenParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "refreshTokenResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "refreshTokenResponse")
    public SSOwsResult refreshToken(
        @WebParam(name = "refreshToken", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "refreshTokenParameters")
        RefreshTokenParameters refreshTokenParameters);

    /**
     * 
     * @param string
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "getGroupsProtectingResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getGroupsProtectingResponse")
    public SSOwsResult getGroupsProtecting(
        @WebParam(name = "getGroupsProtecting", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "string")
        String string);

    /**
     * 
     * @param getGroupsProtectingHostURLParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "getGroupsProtectingHostURLResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "GetGroupsProtectingHostURLResponse")
    public SSOwsResult getGroupsProtectingHostURL(
        @WebParam(name = "getGroupsProtectingHostURL", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "GetGroupsProtectingHostURLParameters")
        GetGroupsProtectingHostURLParameters getGroupsProtectingHostURLParameters);

    /**
     * 
     * @param integer
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "testTimeOutResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "testTimeOutResponse")
    public SSOwsResult testTimeOut(
        @WebParam(name = "testTimeOut", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "integer")
        int integer);

    /**
     * 
     * @param passwordResetKeyParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "getUserPasswordResetKeyResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getUserPasswordResetKeyResponse")
    public SSOwsResult getUserPasswordResetKey(
        @WebParam(name = "getUserPasswordResetKey", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "passwordResetKeyParameters")
        PasswordResetKeyParameters passwordResetKeyParameters);

    /**
     * 
     * @param deactivateInstructorParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "deactivateInstructorResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "deactivateInstructorResponse")
    public SSOwsResult deactivateInstructor(
        @WebParam(name = "deactivateInstructor", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "deactivateInstructorParameters")
        CrmsParameters deactivateInstructorParameters);

    /**
     * 
     * @param reactivateInstructorParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "reactivateInstructorResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "reactivateInstructorResponse")
    public SSOwsResult reactivateInstructor(
        @WebParam(name = "reactivateInstructor", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "reactivateInstructorParameters")
        CrmsParameters reactivateInstructorParameters);

    /**
     * 
     * @param crmsParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "suspendInstructorResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "suspendInstructorResponse")
    public SSOwsResult suspendInstructor(
        @WebParam(name = "suspendInstructor", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "crmsParameters")
        CrmsParameters crmsParameters);

    /**
     * 
     * @param validatedInstructorParameters
     * @return
     *     returns com.tl.ssows.ws.SSOwsResult
     */
    @WebMethod
    @WebResult(name = "validatedInstructorResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "validatedInstructorResponse")
    public SSOwsResult validatedInstructor(
        @WebParam(name = "validatedInstructor", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "validatedInstructorParameters")
        ValidatedInstructorParameters validatedInstructorParameters);

    /**
     * 
     * @param getDirectGroupMembershipParameters
     * @return
     *     returns com.tl.ssows.ws.GetDirectGroupMembershipResult
     */
    @WebMethod
    @WebResult(name = "getDirectGroupMembershipResponse", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getDirectGroupMembershipResponse")
    public GetDirectGroupMembershipResult getDirectGroupMembership(
        @WebParam(name = "getDirectGroupMembership", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", partName = "getDirectGroupMembershipParameters")
        GetDirectGroupMembershipParameters getDirectGroupMembershipParameters);

}
