
package com.thomsonlearning.ws._80.ssows;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SSOws", targetNamespace = "http://ws.thomsonlearning.com:80/ssows", wsdlLocation = "http://s-ws.cengage.com/ssows/SSOws?WSDL")
public class SSOws
    extends Service
{

    private final static URL SSOWS_WSDL_LOCATION;
    private final static WebServiceException SSOWS_EXCEPTION;
    private final static QName SSOWS_QNAME = new QName("http://ws.thomsonlearning.com:80/ssows", "SSOws");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://s-ws.cengage.com/ssows/SSOws?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SSOWS_WSDL_LOCATION = url;
        SSOWS_EXCEPTION = e;
    }

    public SSOws() {
        super(__getWsdlLocation(), SSOWS_QNAME);
    }

    public SSOws(WebServiceFeature... features) {
        super(__getWsdlLocation(), SSOWS_QNAME, features);
    }

    public SSOws(URL wsdlLocation) {
        super(wsdlLocation, SSOWS_QNAME);
    }

    public SSOws(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SSOWS_QNAME, features);
    }

    public SSOws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SSOws(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SSOwsPort
     */
    @WebEndpoint(name = "SSOwsPort")
    public SSOwsPort getSSOwsPort() {
        return super.getPort(new QName("http://ws.thomsonlearning.com:80/ssows", "SSOwsPort"), SSOwsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SSOwsPort
     */
    @WebEndpoint(name = "SSOwsPort")
    public SSOwsPort getSSOwsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.thomsonlearning.com:80/ssows", "SSOwsPort"), SSOwsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SSOWS_EXCEPTION!= null) {
            throw SSOWS_EXCEPTION;
        }
        return SSOWS_WSDL_LOCATION;
    }

}
